package repository

import (
	"fmt"
	"path/filepath"
	"testing"
)

/*
 * Auto generated by Quickstart.
 * Developer to replace the generated test cases with real ones.
 */
func TestSchemaLoader(t *testing.T) {

	path := filepath.Join("testdata", "schemas") // relative path
	absPath, err := filepath.Abs(path)

	if err != nil {
		t.Fatal(err)
	}

	fmt.Printf("\nAbsolute path:%s", absPath)

	schemaRepo := &SchemaLocalRepository{}
	schemaMap, err := schemaRepo.LoadSchemas(absPath)
	if err != nil {
		t.Fatal("Expect successful but failed")
	} else {
		t.Log("Success")
	}
	fmt.Printf("%v", schemaMap)
}
